#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
#    service-url:
#      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
#      #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
#      defaultZone: http://peer2:8002/eureka/,http://peer3:8003/eureka/
#    #默认情况下erureka server也是一个eureka client ,必须要指定一个 server
#    #下面两个配置选项表示自己是一个eureka server
#    register-with-eureka: true
#    fetch-registry: true
#  #SpringClound eurekaServer的自我保护机制，可以在开发模式中关闭
#  server:
#    enable-self-preservation: false
#spring:
#  application:
#    name: EruekaServer #服务的名字
#server:
#  port: 8001

spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8003
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
    fetch-registry: true
    register-with-eureka: true