spring:
  cloud:
    inetutils:
      defaultIpAddress: 10.10.10.11
  application:
    name: eureka.server
eureka:
  instance:
    hostname: 10.10.10.11
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
    defaultZone:${spring.application.name}:${eureka.instance.hostname}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 20000
server:
  port: 8761
