#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
#    service-url:
#      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
#      #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
#      defaultZone: http://euraka1:${server.port}/eureka/,http://euraka2:8002/eureka/,http://euraka3:8003/eureka/
#    #默认情况下erureka server也是一个eureka client ,必须要指定一个 server
#    #下面两个配置选项表示自己是一个eureka server
#    register-with-eureka: true
#    fetch-registry: false
#  #SpringClound eurekaServer的自我保护机制，可以在开发模式中关闭
#  server:
#    enable-self-preservation: false
#spring:
#  application:
#    name: EruekaServer #服务的名字
#server:
#  port: 8001


spring:
  application:
    name: microservice-discovery-eureka-ha #服务的名字
  profiles:
    active:  peer1                     # 指定profile=peer1
server:
  port: 9001
eureka:
  instance:
    hostname: peer1                               # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:9002/eureka/,http://peer3:9003/eureka/      # 将自己注册到peer2这个Eureka上面去
    fetch-registry: true
    register-with-eureka: true
#spring:
#  profiles: euraka2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: euraka2
#  client:
#    serviceUrl:
#      defaultZone: http://euraka1:8761/eureka/
