spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8001
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer3:8003/eureka/,http://peer2:8002/eureka/
    fetch-registry: true
    register-with-eureka: true