spring:
  application:
    name: microservice-discovery-eureka-ha #服务的名字
server:
  port: 9002
eureka:
  instance:
    hostname: peer2                               # 指定当profile=peer1时，主机名是peer1
  client:
    serviceUrl:
      defaultZone: http://peer3:9003/eureka/,http://peer1:9001/eureka/      # 将自己注册到peer2这个Eureka上面去
    fetch-registry: true
    register-with-eureka: true
