spring:
  application:
    name: eureka.server
  profile:
    active: node1
eureka:
  instance:
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 20000
---
spring: 
  profiles: node1
  cloud:
    inetutils:
      defaultIpAddress: 10.10.66.56
server:
  port: 8761
eureka:
  instance:
    hostname: 10.10.66.56
  client:
    serviceUrl: 
      defaultZone: http://10.10.64.38:8761/eureka
---
spring: 
  profiles: node2
  cloud:
    inetutils:
      defaultIpAddress: 10.10.66.56
server:
  port: 8761
eureka:
  instance:
    hostname: 10.10.66.56
  client:
    serviceUrl: 
      defaultZone: http://10.10.64.38:8761/eureka